### ISSUE TITLE
Clear Instructions for Running Eval & Sample Inference 

### ISSUE THREAD

**Issue by TouqeerAhmad** [WHU-USI3DV/SparseDC#3]
Hello, 

I think the instructions for running the eval e.g., for nyudepthv2 should be clearly stated. This is what I have to do myself for running eval on NYUv2: 

After generating the .json file via generate_json_NYUDepthV2.py in NLSPN code, the generated .json file needs to be placed in nyudepthv2 data repo. 
That path then needs to be updated in /SparseDC/configs/paths/default.yaml  and then the eval runs. However, It is running several experiments (different sparsity patterns + different random seeds for generating sparsity) at once and for the full dataset which takes quite a lot of time. 

May be there should be a standalone file that runs these experiment on a subset or on a single image from the dataset to show visual results instead of preparing logs for the whole dataset. That could also give an opportunity to interested readers to evaluate on different test sets or their sample images. May be a simple example without relying on Hydra? 

Thanks!

**Comment by chenlongwhu** [comment]
@TouqeerAhmad, thank you again. I will add the sample Inference code next month. Please be patient.
