### ISSUE TITLE
Tensor Size Mismatch and Missing Keys

### ISSUE THREAD

**Issue by TouqeerAhmad** [WHU-USI3DV/SparseDC#4]
I am noticing some tensor size mismatch and missing keys in the source_dict as the code goes on loading the ViT (pvt_v2_b1). Can you please confirm if this is Okay? I am skeptical, as I had a bit of different environment: 

Ubuntu 22.04
CUDA 11.7 
PyTorch 1.30

And concerned if the mismatch and missing keys I am seeing is due to versioning. I was able to run the evaluation code for nyudepthv2 for all the sparsity patterns as specified in eval_nyu.sh 

Thanks!

**Comment by chenlongwhu** [comment]
Hey @TouqeerAhmad, I think this problem is the same as #2
