### ISSUE TITLE
Bug While Running Eval on SUNRGBD

### ISSUE THREAD

**Issue by TouqeerAhmad** [WHU-USI3DV/SparseDC#5]
Hello,

I downloaded the SUNRGBD dataset from your provided Google Drive link. But running  `./eval_sunrgbd.sh final_version final_version pretrain/nyu.ckpt` with path properly set in the default.yaml, code throws error on /SparseDC/src/data/sunrgbd.py at line 48. 

Looking into that file, It looks like it is expecting to see a folder with 'train_depth' in the SUNRGBD directory but that directory has the following structure and no such folder is available. 

|-- 
|-- SUNRGBD
|-- |---test_depth_gt
|-- |---test_depth_input
|-- |---test_images
|-- |---train_depth_gt
|-- |---train_depth_input
|-- |---train_images

Please advise how to proceed?

**Comment by chenlongwhu** [comment]
@TouqeerAhmad Thank you very much for your attention, Sorry about this mistake, you can simply replace the line 48 with
```
self.file_name = os.listdir(os.path.join(self.data_dir, "test_depth"))
```
 I haven't had time to fully optimize my code yet, but I will optimize this repo in the next month.

**Comment by TouqeerAhmad** [comment]
Thank you for clarifying

**Comment by LiuQiir** [comment]
Why am I not able to fix it by following the above? May I ask how you solved this problem? Thanks！！！

**Comment by LiuQiir** [comment]
> @LiuQiir Can you provide more error details?
When I replace the 48 lines of code, I still get the error reported.
<img width="524" alt="修改！！" src="https://github.com/WHU-USI3DV/SparseDC/assets/116939982/ed60d0a1-5de8-49a2-b1bb-f98b78c5f09d">
error：
![image](https://github.com/WHU-USI3DV/SparseDC/assets/116939982/76be7330-134c-4ca4-8af4-1212fd282d18)

**Comment by LiuQiir** [comment]
> @LiuQiir Can you provide more error details?

When I replace the 48 lines of code, I still get the error reported.
<img width="524" alt="修改！！" src="https://github.com/WHU-USI3DV/SparseDC/assets/116939982/ed60d0a1-5de8-49a2-b1bb-f98b78c5f09d">

error：
<img width="517" alt="错误111" src="https://github.com/WHU-USI3DV/SparseDC/assets/116939982/d217afc1-c8ea-42b7-8e8a-a2282e0c3a47">

**Comment by chenlongwhu** [comment]
@LiuQiir, Sry about it; you can first check the dir structure under SUNRGBD to see whether there is "test_depth" in this folder; if not, you can replace "test_depth" with "test_depth_gt“. This error occurs because  I made a mistake with the folder's name 😭😭😭, but this mistake will not affect the final test result.

**Comment by LiuQiir** [comment]
> @LiuQiir, Sry about it; you can first check the dir structure under SUNRGBD to see whether there is "test_depth" in this folder; if not, you can replace "test_depth" with "test_depth_gt“. This error occurs because I made a mistake with the folder's name 😭😭😭, but this mistake will not affect the final test result.

Thanks！！！
<img width="748" alt="解决！！！" src="https://github.com/WHU-USI3DV/SparseDC/assets/116939982/5b297193-dfae-4615-aadc-a17c873fb7e8">

**Comment by chenlongwhu** [comment]
@LiuQiir , You're welcome 😁😁😁. As you can see, the code of this repo is not perfect. I will optimize it after the paper is accepted.
