### ISSUE TITLE
How to eval on my own data?

### ISSUE THREAD

**Issue by Contrail97** [WHU-USI3DV/SparseDC#7]
Hi there, thinks your excellent work, im appericiate for you released the code. Im wondering how to get the dense depth map on my own dataset?

**Comment by chenlongwhu** [comment]
> Hi there, thinks your excellent work, im appericiate for you released the code. Im wondering how to get the dense depth map on my own dataset?

Hi, you can modify you own dataloader file, and use the trainer.infer function of pytorch_lightning.
